# Generated by Django 4.1.1 on 2022-12-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_qoute',
        ),
        migrations.RemoveField(
            model_name='country',
            name='description',
        ),
    ]
